### ISSUE TITLE
NancyFx/Nancy

### ISSUE THREAD

**Issue by FoggyFinder** [fsprojects/awesome-fsharp#55]
Just curious how NancyFx/Nancy related to F#?

**Comment by eugene-g** [comment]
Always had the same question. Probably, should make a PR to remove them.

**Comment by VPashkov** [comment]
Maybe we should aslo remove Akka.NET and ASP.NET Core MVC?

**Comment by pmbanka** [comment]
@VPashkov Akka.NET has a built-in support for F#:

https://www.nuget.org/packages/Akka.FSharp/
https://github.com/akkadotnet/akka.net/tree/dev/src/core/Akka.FSharp  (note it is under "core")

so I'd say it should stay (or at least Akka.FSharp NuGet package should stay). No strong feelings about ASP.NET Core MVC though.

**Comment by eugene-g** [comment]
@pmbanka is Akka.FSharp awesome enough to belong to Awesome F# list?

**Comment by pmbanka** [comment]
@eugene-g it is a layer over regular Akka API which makes using Akka from F# nicer experience. It is officially supported and even mentioned on getakka.net website, which is nice.

**Comment by pmbanka** [comment]
@eugene-g 

> Orleans and Akka are not F# projects

I think that this list should include projects that have some features that make them nicer to use from F# (compared to regular C# library). That way we avoid listing here all .Net libs. So, for example:
- Akka - keep, because of Akka.FSharp (or just mention Akka.FSharp, since it is technically a separate NuGet package). In that case I'd probably go for including Akka since FSharp part is a part of core of the project, but both options are ok.
- Orleans - leave out, no F# specific API (as far as I know) BUT
- Orleanakka - keep - nice F# API for Orleans
- Newtonsoft.Json - keep - support F# types http://james.newtonking.com/archive/2014/04/30/json-net-6-0-release-3-serialize-all-the-f
- Serilog - leave out, no F# specific API  (as far as I know) BUT
- Destructurama.FSharp - keep, since it enhances Serilog with exactly that https://www.nuget.org/packages/Destructurama.FSharp/
etc.

But that's just like, my opinion, man ;)

**Comment by FoggyFinder** [comment]
well, MathNet.Numerics not F#-written  too, but has nice F# API so I think it can be at list
